name: SmartCampus Web App
version: 1.0
description: >
  A modern multi-role school platform for students, teachers, and admins to
  manage bookings, announcements, grades, and more.
author: Letago Semenya
tech_stack:
  - HTML
  - CSS
  - JavaScript
  - VS Code
  - GitHub
entry_point: index.html
pages:
  - index.html
  - select-account.html
  - student.html
  - teacher.html
  - admin.html
  - booking.html
  - grades.html
  - alerts.html
  - resources.html
  - about.html
  - upload.html
  - students.html
  - contact.html
output: web
license: MIT
